### ISSUE TITLE
Call for 🗣project interviewees 📹🎤

### ISSUE THREAD

**Issue by doctorrobinson** [ipfs/camp#100]
### Hello fellow campers!

Last year at our developers meetings we had the opportunity to sit down with some of our users to [talk about their projects](https://youtu.be/G3ebPkJaniQ), IPFS and what they love about their work. This year we're looking to expand on that and I need your help to do it.

So this is your chance to talk about the great work you've been doing! I'd like to hear all about your project, discuss how it works, why you chose IPFS, and hear some highlights about any breakthroughs or unique aspects of what you're doing. In the end, we'll edit them into an IPFS story that focuses on your work - for you to share with the world. 

These interviews will be happening outside regular workshop hours and I expect to take 15-20 minutes, so you won't be missing out on events. 

Location TBD, but it'll be near the workshops.

If you're interested, please go ahead and toss yourself in an open slot, and if you can't find a slot, drop a comment and I'll reach out to find a time that works for us. I'll be adding the general questions here later today for anyone who wants to practice (but don't feel obligated to). 

Location: Andrea Polli, next to the workshop classrooms
![andrea](https://user-images.githubusercontent.com/6369871/60374615-479afe80-99d3-11e9-8b90-1ab4db8fa919.jpg)

Friday, June 28 | Interviewee | Company/Project
-- | -- | --
19:30 | @b5  | [QRI.io](qri.io)
20:00 | @ianopolous  | Peergos
20:30 | @hareeshnagaraj | [audius](https://audius.co/)
21:00 | @steven004 |  IPFS-Force
21:30 | @apronkin | [Anytype](https://anytype.io)

Saturday, June 29 | Interviewee | Company/Project
-- | -- | --
19:30 | @blackforestboi | [worldbrain.io](worldbrain.io)
20:00 | @hinshun  | netflix
20:30 | @rklaehn | actyx.io
21:00 | @jkarni | (radicle/Monadic)
21:30 | @vasa-develop | Cluster Labs(https://clusterlabs.io)

**Comment by ianopolous** [comment]
I could do 20:00 on Friday - Peergos

**Comment by steven004** [comment]
I could do at 21:00 on Friday.

@Steven004   IPFS-Force

Best Regards,
Steven

**Comment by rklaehn** [comment]
I can do Saturday, 20:30

@rklaehn [actyx.io](https://www.actyx.io/en/)

Thanks,
Rüdiger

**Comment by vasa-develop** [comment]
I can do Saturday 21:30 - Cluster Labs(https://clusterlabs.io)

**Comment by requilence** [comment]
Can you please add @apronkin from [Anytype](https://anytype.io) for the last slot at 28th 21:30?

**Comment by doctorrobinson** [comment]
Location: Andrea Polli, next to the workshop classrooms

**Comment by jkarni** [comment]
I could do Saturday at 21:00 ([radicle](https://radicle.xyz/)/Monadic)

**Comment by doctorrobinson** [comment]
If anyone else is available or interested, please post here. There's likely to be cancellations, or a chance to open up other times!

**Comment by doctorrobinson** [comment]
![andrea](https://user-images.githubusercontent.com/6369871/60374597-36ea8880-99d3-11e9-8268-46189499a007.jpg)

Location of the room.

**Comment by doctorrobinson** [comment]
Closing this issue and moving media feedback to thread https://github.com/ipfs/camp/issues/141 for both sci-fi and interviews.
