### ISSUE TITLE
💻 Preparation for Camp 🎒

### ISSUE THREAD

**Issue by daviddias** [ipfs/camp#101]
Hi y'all @ipfs/ipfs-camp-2019-attendees 👋🏽

We are almost at Camp! YEaaASs 🙌🏽 🙌🏽 🙌🏽 The event starts tomorrow and we are super excited to meet everyone in person!

### We have a tremendous amount of Content ready for you 

<img width="1167" alt="Screenshot 2019-06-26 at 13 07 41" src="https://user-images.githubusercontent.com/1211152/60175329-8f732780-9813-11e9-82b4-3285d329a965.png">

### Produced by a fantastic group of 67 humans which we are incredibly thankful for

<img width="1337" alt="Screenshot 2019-06-26 at 13 04 49" src="https://user-images.githubusercontent.com/1211152/60175333-939f4500-9813-11e9-8016-7ac3999a76a1.png">

### In order to make the most out of the sessions at Camp and value the hard work all the content creators put into creating the sessions for you, we kindly ask you to go through the Preparation Checklist the Content Creators left for you, so that you can bring your laptops fully ready 💻 ✨ 💡, that's just it :) 

These checklists can be found at:

- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_B#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_C#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_D#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_A#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_B#installation-instructions
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_C#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_D#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_E#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_F#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_G#preparation-for-the-course
- https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_H#preparation-for-the-course

If you hit any obstacle through the preparation, please let us know :) We can help you right on this issue, the [camp chat](https://github.com/ipfs/camp#join-the-chat-at-ipfs-campfreenode-using-any-irc-client-or-through-the-matrix-bridge) and/or at Camp, we will also have an help desk :)

Thank you!

**Comment by vasa-develop** [comment]
Hi @daviddias

Just to be clear,

1) how many CORE courses can an individual attend?

2) how many ELECTIVE courses can an individual attend?

Thanks ;)

**Comment by autonome** [comment]
Hi @vasa-develop! Attendees can take all four core courses, and two of the elective courses. You can see how this is scheduled here: https://camp.ipfs.io/schedule/
