### ISSUE TITLE
Interested in Headshots?

### ISSUE THREAD

**Issue by yunigraham** [ipfs/camp#107]
Hi Campers! 

I'm offering free headshots today and tomorrow for anyone who is interested.
These will be taken outside regular workshop hours and I expect to take ~10 minutes, so you won't be missing out on events.

Location will be right outside Mas Bonvilar where you entered the space tunnel :)  

If you're interested, please go ahead and sign up in an open slot. If you can't find a slot, comment below, and I'll reach out to find a time that works for us.

Friday, June 28 | Name | Company/Project
-- | -- | --
19:30 | @vojtechsimetka  | 
19:40 |   | 
19:50 |  | 
20:00 |  | 
20:10 |  | 
20:20 |
20:30 |

Saturday, June 29 | Name | Company/Project
-- | -- | --
19:45 |   | 
19:55 |   | 
20:05 |  | 
20:00 |  |

**Comment by vojtechsimetka** [comment]
Friday 19:30 but pretty flexible time-wise

@vojtechsimetka
[RIF Storage](https://www.rifos.org/framework/)

**Comment by yunigraham** [comment]
Hi Vojtech, 

Awesome! If you are a bit early before the poster session, we could take 3 - 5 mins to do it in the lounge area of Mas Bonvilar. The lighting in there is pretty great :) Otherwise we can wait til our next break or after the day is done. Just come find me. 🦄

**Comment by momack2** [comment]
Thanks for the gorgeous headshot, @yunigraham!!!

**Comment by reqsa1990** [comment]
hai
