### ISSUE TITLE
Slides for Core Courses? (and electives?)

### ISSUE THREAD

**Issue by nuke-web3** [ipfs/camp#108]
It would be awesome to be able to recap! Can we have the leads for each session add any presentation and supplemental materials? :pray:

**Comment by hareeshnagaraj** [comment]
+1, this would be great

**Comment by terichadbourne** [comment]
Agreed! I've actually been connecting with some of the course leaders to track these down lately as a I work on [figuring out which content would be a good fit for ProtoSchool](https://github.com/ProtoSchool/protoschool.github.io/issues/261), so I'd be happy to start a PR to add the ones I've located so far and we can go from there.

**Comment by autonome** [comment]
From the course dirs here in this repo. Most have installation and prep notes, but not links to slides.

* [x] Elective A: Identity on the DWeb - @satazor | @paulobmarcos | @joaosantos15
* [x] Elective B: Managing pinsets with IPFS Cluster - @hsanjuan | @meiqimichelle | @lanzafame
* [ ] ~Elective C: Cat roulette! - @gorhgorh~ _didn't have slides_
* [x] Elective D: Building DApps with Textile - @balupton | @carsonfarmer | @andrewxhill
* [x] Elective E: Deploying IPFS Infrastructure - @obo20 | @mburns | @kubuxu
* [x] Elective F: Stewarding a local IPFS Community - @nukemandan | @kk3wong | @stefanhans ([Slides](https://docs.google.com/presentation/d/1OLmSfOMjffl7z2ODxHaBcQBmyVEGdt8O7h3bxYv_VVI/edit?usp=sharing))
* ~[ ] Elective G: Managing Datasets with QRI - @b5~ no relevant slides to share
* [x] Elective H: Making the Browser a True User Agent - @autonome | @Gozala | @soapdog ([Slides](https://hackmd.io/@dietrich/rkrZEKFRV))

**Comment by hsanjuan** [comment]
Added Elective B.

**Comment by satazor** [comment]
Added Elective A slides: https://github.com/ipfs/camp/pull/181

**Comment by carsonfarmer** [comment]
We already had links to our slides in our README, but I've added an explicit link and mention there now to help folks find them! Thanks for the prompt 👍

**Comment by terichadbourne** [comment]
@carsonfarmer I see a "Slides and materials" link within the Elective D repo that goes here: https://github.com/textileio/ipfs-camp-2019, but once I'm there it's not obvious to me where to find the slides. I tried clicking into the "workshop" folder there but there's still nothing jumping out at me. Do you have a link that goes directly to a slide deck by chance?

**Comment by terichadbourne** [comment]
I've just merged an edit to the ipfs/camp readme to update the table to surface links to slides. Already included are all core courses and electives A and F. There's a PR open to add those for electives B & H (#182) and I'm not able to find my way to the slide deck for D.  

When adding links to slide decks moving forward, please be sure to add them both within your course repos and in this primary table for quick access (see an example below). Thanks!

![image](https://user-images.githubusercontent.com/19171465/64348861-ed667d00-cfc3-11e9-8e93-c24ec7766c90.png)

**Comment by terichadbourne** [comment]
We're missing slide decks for these elective courses. Could the leaders please let us know if there are decks available to share? 
- @gorhgorh - Cat Roulette 
- @b5 - Managing Datasets with QRI 
- @obo20  @mburns @Kubuxu - Deploying IPFS Infrastructure 

- @carsonfarmer @balupton @andrewxhill** Building DApps with Textile 
I'm personally still having trouble finding the slide deck for this one despite seeing it referenced in the repo, so it may make sense to choose a different link.  If I click through a few links to https://github.com/textileio/ipfs-camp-2019/tree/master/workshop then I see this statement in the readme: "Slides are Markdown Slides, based on Reveal.js markdown format. Recommend viewing them using vscode-reveal in VSCode." Does this mean that the [markdown.md file](https://github.com/textileio/ipfs-camp-2019/blob/master/workshop/markdown.md) served as your slide deck? Is there any way to export a PDF while using RevealJS or would you prefer to just share the markdown file?

Thank you all!

**Comment by b5** [comment]
Hi @terichadbourne, 

Apologies, Our elective didn't have a deck that would make sense outside of the course itself.  Hope that helps!

**Comment by terichadbourne** [comment]
Gotcha. Thanks for the update @b5!

**Comment by gorhgorh** [comment]
hi there @terichadbourne catroulette elective course did not really had slides, this is a terminal based workshop.

**Comment by terichadbourne** [comment]
Thought that might be the case, @gorhgorh. Thanks so much for confirming!

**Comment by obo20** [comment]
Hey all, sorry for the delay on this. I just saw this in my email inbox. Here's a link to our slides
[Deploying IPFS Infrastructure - IPFS Camp.pdf](https://github.com/ipfs/camp/files/3623595/Deploying.IPFS.Infrastructure.-.IPFS.Camp.pdf)

**Comment by terichadbourne** [comment]
Thanks for that link @obo20. I've added this to your repo. 

@doctorrobinson kindly added links to all videos from both the course listings and each course's repo for all that have videos (elective H doesn't). 

We technically now have links to slide decks for all that had them (electives C and G didn't), although I still find the slide deck for elective D hard to surface. 

@carsonfarmer @balupton @andrewxhill
I'm personally still having trouble finding the slide deck for your elective course despite seeing it referenced in the repo, so it may make sense to choose a different link. If I click through a few links to https://github.com/textileio/ipfs-camp-2019/tree/master/workshop then I see this statement in the readme: "Slides are Markdown Slides, based on Reveal.js markdown format. Recommend viewing them using vscode-reveal in VSCode." Does this mean that the markdown.md file served as your slide deck? Is there any way to export a PDF while using RevealJS or would you prefer to just share the markdown file?  Is there any need for folks looking for workshop materials to visit your [broader repo about all of your IPFS Camp materials](https://github.com/textileio/ipfs-camp-2019), as is now suggested, or could they go directly to your [workshop folder](https://github.com/textileio/ipfs-camp-2019/tree/master/workshop) and still find what they need? I'm happy to be the one to update links if that sounds reasonable.

**Comment by terichadbourne** [comment]
Quick update: @carsonfarmer is working on a PDF of the slide deck for Elective D for us so we can make it a little easier to locate. 🎉

Once we get that shared we should be able to close out this issue.

**Comment by 0zAND1z** [comment]
Great! 

For everybody's benefit in this thread, here is the PR: https://github.com/ipfs/camp/pull/199

**Comment by terichadbourne** [comment]
All available slides and videos for core and elective courses are now linked both from the [main course listings](https://github.com/ipfs/camp#-core--elective-courses--youtube-playlist) and from individual course repos. Thanks to all the instructors for making these resources available!
