### ISSUE TITLE
📹 Record a high quality presentation of your project! 📣

### ISSUE THREAD

**Issue by daviddias** [ipfs/camp#132]
Hi IPFS Campers! We are so pumped by all the amazing projects, lighting talks, Sci-Fi projects and demos that you have been showing throughout the event, that it dawned on us that you might fancy recording a high quality presentation that then can be broadcasted to the entire IPFS Community for multiple generations! How does that sound? :D

We are flexible on time, these can go from 5 to 15 minutes and depending on demand, we can arrange a way to parallelize these recordings.

The presentation rooms will be set up in ~~the same floor that the Core & Elective courses were.~~ Mas Bonvillar (Main room), where the Graduation Ceremony will be. 

We will be available to record your presentations from 8am to 8:45am.

To register for a recording, please post a comment in this issue with:

- Title
- Contact name (GitHub handle)
- Length (5~15 mins)
- Preferred time

We will keep the following table updated with slots allocation!

| Time 		| Contact 	| Title 	|
|------		|------		|-------	|
| 8:00am   	| @aschmahmann | Fast IPNS      	|
| 8:15am    	| @satazor      |  Showcasing Identity Manager and Nomios     	|
| 8:30am   	| @obo20       | IPFS Industry Trends |

Second option, doing it during the Lunch Hour (12:00h to 13:00). **This option might cause you to miss 1pm shuttle.**

For the afternoon we have:

- @andrewxhill  Textile  
- @janjanovna  Anytype

**Comment by doctorrobinson** [comment]
@daviddias I'm also happy to do 8:00-9:00 in the plenary room if that's preferable, we could get a couple presentations in as we head directly into the start of the day?

**Comment by vasa-develop** [comment]
Can I send the recording of the video to you, which can be published via ipfs channels? I want to show a few things that aren't built right now, but I will build them in couple of days. Does that sound ok?

**Comment by satazor** [comment]
Title: Showcasing Identity Manager and Nomios
Contact: @satazor 
Length: 10-15m
Preferred time: 10:30am (I will also be reporting on the deep dive)

**Comment by obo20** [comment]
Title: IPFS Industry Trends
Contact name (GitHub handle): obo20
Length (5~15 mins): 10
Preferred time: 8:45

**Comment by daviddias** [comment]
@satazor did you mean 10am or 8am? I've added you for 8:15am, hope that is ok
@obo20 added you for 8:30 (8:45 is when we have to end).

**Comment by andrewxhill** [comment]
We are in for the latest slot you’ll give us!

**Comment by aschmahmann** [comment]
@daviddias Can I grab the slot before @satazor/the latest available slot 😄?
Title: Fast IPNS using PubSub
Contact name: @aschmahmann 
Length: 5-10min

@andrewxhill beat me to it, so I guess I'll get the slot before him 😆

**Comment by jbenet** [comment]
I think @janjanovna from Anytype wanted to do this too— will let her comment here

**Comment by doctorrobinson** [comment]
Hey everyone - I'm about to head to bed, so @daviddias I'll be in Mas Bonvilar at 7:45am and setting up, with expectation of an 8am start. Please schedule people appropriately, and I can also stay after the last session at noon to record a few talks, as I will be taking the shuttle back and don't need to leave promptly at 1pm. 

Please be on time - if you're late and it conflicts with another presentation we'll have to cut you off so we can respect the schedule. 

See you all in the morning.

**Comment by janjanovna** [comment]
I'd love to make a short 5 min demo of Anytype, and would also prefer the latest slot of possible options :)

**Comment by janjanovna** [comment]
@daviddias So, I'd prefer after the talks tomorrow as you suggested as an option

**Comment by andrewxhill** [comment]
Staying in Barcelona tomorrow night too so could also go after the main track, no hurry

**Comment by daviddias** [comment]
Hi all! I've updated the schedule accordingly, see my first comment again: https://github.com/ipfs/camp/issues/132#issue-462326929

@andrewxhill @janjanovna moved you to post event session. Please check in with @doctorrobinson when you get to the venue to confirm what time is the best in the afternoon.

**Comment by doctorrobinson** [comment]
There's a slot at 8:45 for someone (i'll be over there already) or you can both go during lunch, 12-12:30ish pm. I'm going to work under the assumption you'll both go during lunch.

**Comment by momack2** [comment]
Not quite on topic, but I'd be happy to just chat/interview after the sessions tomorrow if we aren't super rushed (those of us not heading to the airport).

**Comment by ianopolous** [comment]
If the 8:45 slot is still free in the morning could we grab that for Peergos? Otherwise anything in the morning. Thank you!

**Comment by placer14** [comment]
Title: OpenBazaar presents Decentralized Commerce on Mobile
Contact name: @placer14
Length: 5-10min
Preferred time: I'm not clear where the stops are available, please fit us in wherever if possible. :)

**Comment by tetrisgm** [comment]
Hi, I’d like to do one (5 minutes) for Permaweb Writer, latest time possible would work :)
@momack2 would love to chat.

**Comment by daviddias** [comment]
@leshokunin @placer14 @ianopolous would you like to join us at Mas Bonvillar? Just talked with @doctorrobinson and there might be a way to squeeze you in.

**Comment by jbenet** [comment]
We are going now, and have some space — if you were interested and haven’t gone, come to Mas Bonvillar (the main stage).

@rklaehn did you want to talk about or demo Actyx?

**Comment by daviddias** [comment]
Thank you all for preparing a presentation for this recording. We really appreciate it and the community will do as well as soon as they get to see the presentations :D 

Closing this issue for now. All the IPFS Camp recordings will be broadcasted through the IPFS Youtube Channel ~~https://www.youtube.com/user/ipfs~~ https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew and http://camp.ipfs.io/

**Comment by aschmahmann** [comment]
@daviddias that youtube channel is definitely incorrect, do you mean https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew?

**Comment by daviddias** [comment]
Thank you @aschmahmann!

**Comment by doctorrobinson** [comment]
@leshokunin let me know when that demo is ready! We're aiming to get these talks out next week!
