### ISSUE TITLE
Arriving at sunny Barcelona early 🌞? Join us at the Barcelona IPFS Meetup Jun 25

### ISSUE THREAD

**Issue by daviddias** [ipfs/camp#51]
### To welcome everyone that is coming to Barcelona for IPFS Camp and also to have a chance to meet the local IPFS community in Barcelona 🌞 

Join us at:

<a href="https://www.meetup.com/barcelona-ipfs/events/262101190/"><img width="684" alt="image" src="https://user-images.githubusercontent.com/1211152/59526020-2f59b880-8ed8-11e9-8d14-133393d274f9.png"></a>

URL: https://www.meetup.com/barcelona-ipfs/events/262101190/

We still have a couple of slots for lightning talks ⚡️ at the Meetup. If you are interested in talking about your project, apply at: https://protocollabs.typeform.com/to/IEMyVC

**Comment by daviddias** [comment]
Forgot to tag @ipfs/ipfs-camp-2019-attendees :)

**Comment by KeepItCooley** [comment]
Hi folks! Please see the agenda for the **IPFS Core Dev & Community Meetup** below. We still have more slot available for lightning talks ⚡️and would love to hear from the community!

## Agenda
18:00 - 19:00h: Welcome + Drinks
19:00 - 20:30h: Presentations & Lightning Talks & Q + A
20:30 - 21:30h: Networking + Light Appetizers 


## Location 
[MOB Bailèn](https://mob-barcelona.com/) (Makers of Barcelona) 
Carrer de Bailèn, 11, 08010 Barcelona

**Comment by leshokunin** [comment]
I’d love to do a lightning talk. It’d be on the “Dropbox Paper for IPFS”
app I’ve been working on: Permaweb Writer (formerly Epona).

Can we make that happen?

**Comment by momack2** [comment]
@leshokunin - did you mean to add a github response here? I see:

> I’d love to do a lightning talk. It’d be on the “Dropbox Paper for IPFS”
app I’ve been working on: Permaweb Writer (formerly Epona).
Can we make that happen?

as an email response to this issue, but not reflected on github? We can carve out one additional slot if needed, but no pressure! Just wanted to make sure this wasn't falling through the cracks. =]

**Comment by momack2** [comment]
![image](https://user-images.githubusercontent.com/618519/60036889-903f7880-96b0-11e9-8cfc-a615ee9d3f00.png)
^ current agenda

**Comment by tetrisgm** [comment]
Looks like @DrCatman and I are arriving on the 26th (Wednesday) in the morning. Any plans to hang in Barcelona during that day? What are people thinking of doing?
