### ISSUE TITLE
Design Patterns workshop at IPFS Camp

### ISSUE THREAD

**Issue by tetrisgm** [ipfs/camp#62]
Hey,
I had an email thread earlier with @jesseclay @Stebalien @olizilla .
I was wondering if it’d be possible to give a talk at IPFS Camp?

The topic would be Design Patterns for DWeb apps. Ideally I’d love to do a workshop where I do live design, and we solve a real design problem and hopefully people pick up those lessons and I can help implement design during the week.

I’ve done this with Textile, where I worked with Sander to lower the permission and roles system from ~15 methods to 2, resulting in a lot less complexity. Also did that on a number of large scale apps throughout the years.

Would love to teach some Product thinking and UX there!

**Comment by momack2** [comment]
@alanshaw  - this sounds like a deep dive to me (given the interactive, longer-form nature). Can we make it happen? It sounds awesome!

**Comment by alanshaw** [comment]
@leshokunin I've been in contact via email also :) - please send a PR to https://github.com/ipfs/camp/blob/master/DEEP_DIVES/48-design-patterns-for-dweb-apps.md
