### ISSUE TITLE
Permaweb Writer lightning talk

### ISSUE THREAD

**Issue by tetrisgm** [ipfs/camp#71]
Hey, I presented the idea back at Lab Day during the Lightning Talk.
Now we have a release to showcase, which we've built just in time for IPFS Camp.

We'd be showing Permaweb Writer, which is Dropbox Paper on top of IPFS (and Textile).
We've prepared the first public build, and a feature so we can make presentation slides by writing Markdown. Would love to show it off to people so they can see an IPFS app that has a lot of product/frontend/ux work.

Totally happy to ditch a scifi thing for this.

**Comment by jessicaschilling** [comment]
Would this actually be a great sci-fi fair table, so people can play with it? (We are, as of now, full up on lightning talks.)

**Comment by tetrisgm** [comment]
It'd be ok. The format of a scifi table would be less informative imho (since we'd like to cover how we think products can be built on ipfs), but it'd be ok. FYI I thought we were in already because I notified a bunch of people about it (Jesse, Stebalien, Olizilla) back in May, so I'd love if we can make it work.

**Comment by jessicaschilling** [comment]
I think we may have had some crossed wires on our end — let’s see if we can’t squeeze you in (especially considering we may end up with some last-minute cancellations, etc). Can you please let me know your presenter name (you?) and the title of your talk at your earliest convenience, and review the talk guidelines (including due date of Monday) here?: https://github.com/ipfs/camp/blob/master/LIGHTNING_TALKS/README.md
Thanks!

**Comment by tetrisgm** [comment]
Hahaha no worries, I know there's a ton going on. That'd be great.
Presenter name: Shokunin.
Title of the talk: Building a Dropbox replacement on IPFS and Textile
Talk guidelines: reviewed! I can be ready for Monday (slides included, though I'm hoping to do a demo from my laptop and show off the actual build too).
Does that work?

**Comment by jessicaschilling** [comment]
Thank you for the update! The reason that we are requesting all the talks be displayed off one machine is that plugging/unplugging machines adds at least another minute to each talk — and therefore fewer talks can be given. If it’s absolutely essential that a live demo be included rather than video, as described, those folks will be asked to present last to reduce complexity and the chance of their time knock-ons affecting others. With this in mind, a more streamlined option could be to use a recorded demo for the talk and also propose an unconf slot at camp to discuss and demo some option of your work in greater detail.

**Comment by tetrisgm** [comment]
No problem, we can skip the live demo. I’ll simply include images! Would be great to demo at the unconf later but I’ll focus on the lightning talk.

**Comment by tetrisgm** [comment]
Do you have a deck or link to some slides I can use as a starter, or should I just prepare something on my side and send it to you? Where should I send it for Monday?

**Comment by jessicaschilling** [comment]
No need to use a specific template - just do whatever you feel best. Please just mail it to me: jessica@protocol.ai. Thanks!

**Comment by tetrisgm** [comment]
Just to double check: this takes place during IPFS Camp, not the one during the Meetup, right? I'm landing on the 26th in the morning :)

**Comment by jessicaschilling** [comment]
Correct 😊
